services:
  - type: web
    name: farm-app
    runtime: python
    rootDir: backend

    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install uv

      cd ../frontend
      npm ci
      npm run build

      cd ../backend
      uv sync --frozen

    startCommand: uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"

      - key: ENV_TYPE
        value: production