# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13 # Version
    hooks:
      # This will run linting
      - id: ruff
        args: [ --fix ] # Automatically fix unused imports/sorting on commit

      # This will run formatting
      - id: ruff-format